name: marcaii_flutter
description: Gerenciador de Horas Extra

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  lib_observer:
    git:
      url: "https://github.com/bicasoftware/lib_observer"

  cupertino_icons: ^0.1.2
  provider: ^4.0.2
  rxdart: ^0.23.1
  dio: ^3.0.8
  retrofit: ^1.0.1+1
  sqflite: ^1.2.0
  morpheus: ^1.2.2+1
  jiffy: ^2.2.0
  json_serializable: ^3.2.5
  path_provider: ^1.5.1
  path: ^1.6.4
  flutter_secure_storage: ^3.3.1+1
  card_settings: ^1.5.5
  intl:
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner: any
  retrofit_generator: any

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
