name: marcaii_flutter
description: Gerenciador de Horas Extra

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_native_splash:
  image: assets/images/logo.png
  color: "F35423"
  ios: false

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  lib_observer:
    git:
      url: "https://github.com/bicasoftware/lib_observer"

  cupertino_icons: ^0.1.2
  line_awesome_icons: ^1.0.4+2
  provider: ^4.0.2
  rxdart: ^0.23.1
  dio: ^3.0.8
  retrofit: ^1.0.1+1
  sqflite: ^1.2.0
  jiffy: ^2.2.0
  json_serializable: ^3.2.5
  path_provider: ^1.6.7
  path: ^1.6.4
  flutter_secure_storage: ^3.3.1+1
  auto_size_text: ^2.1.0
  intl:
  bubble_bottom_bar: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner: any
  retrofit_generator: any
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
