name: marcaii_flutter
description: Gerenciador de Horas Extra

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

flutter_native_splash:
  image: assets/images/logo.png
  color: "F35423"
  ios: false

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_utils:
    git:
      url: https://github.com/bicasoftware/flutter_utill

  line_awesome_icons: ^1.0.4+2
  rxdart: ^0.24.1
  dio: ^3.0.10
  sqflite: ^1.3.1+1
  jiffy: ^3.0.1
  path_provider: ^1.6.14
  path: ^1.7.0
  flutter_secure_storage: ^3.3.3
  auto_size_text: ^2.1.0
  intl: ^0.16.1
  animations: ^1.1.2
  provider: ^4.3.2+1
  retrofit: ^1.3.4+1
  connectivity: ^0.4.9+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner: null
  retrofit_generator: ^1.3.8+3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png
    - assets/images/salario.png
    - assets/images/cargahoraria.png
    - assets/images/calendar.png
    - assets/images/diferenciadas.png
    - assets/images/fechamento.png
    - assets/images/forms.png
    - assets/images/porcentagens.png
    - assets/images/descricao.png
    - assets/images/emprego.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
